### ISSUE TITLE
clone() implementation in op.js

### ISSUE THREAD

**Issue by sachinrekhi** [ottypes/rich-text#17]
I was reviewing your reference implementation as I'm porting the rich-text ottype to Python and wanted to check-in on something.

The implementation of **clone()** in op.js is the following:

```
clone: function (op) {
    var newOp = this.attributes.clone(op);
    if (typeof newOp.attributes === 'object') {
      newOp.attributes = this.attributes.clone(newOp.attributes, true);
    }
    return newOp;
  },
```

I think your intention is to effectively perform a deep copy of the op. It seems to accomplish this by doing a shallow copy and then special-casing **attributes** since it knows it is an object and does a separate shallow-copy on it's contents.

While this mostly works, seems like you could run into issues when copying an op that represents a new Quill 1.0-style insert embed operation. Since in this case the value of the insert key is itself an object, like the attributes case, you currently would end up just copying the reference but not deep-copying the individual object keys. Am I correct?

**Comment by jhchen** [comment]
Attributes has to be cloned because rich-text might modify it whereas I believe embeds are only compared for equality. There might potentially be issues as I do not recall explicitly making the shallow copy decision but thinking about it more now it's not obvious if that is right or wrong.

```js
var myEmbed = { 
  video: { 
    src: 'youtube.com/abcd',
    width: 400, 
    height: 400 
  } 
};

var deltaA = new Delta().insert(myEmbed);
// some change to myEmbed
var deltaB = new Delta().insert(myEmbed);

deltaB.diff(deltaA);
```

In this example it's not obvious what `diff` should report here, which is determined by a shallow or deep copy. To me if `width` was changed, diff should report no change; if `src` was changed, it should. But rich-text needs to not care about what its fields mean so it's behavior cannot depend on this. One could argue that `width` and `height` should be attributes as attributes are meant for more malleable descriptors so I'm leaning towards accepting a deep copy as correct but I'll have to think about it more and circle back. If you have more clarifying examples feel free to post.

**Comment by thomsbg** [comment]
I use a forked version of rich-text that supports [deep comparison of attributes](https://github.com/ottypes/rich-text/commit/42491206be4cd979e14d2d6d7ea57225d2260f65), because I have several formats that use nested attribute keys, e.g.

```
{
  insert: 1,
  attributes: {
    image: {
      id: 1234,
      src: 'http://i.imgur.com/XLnYgMy.jpg',
      caption: 'what a time to be alive'
    }
  }
}
```

Deep comparison is necessary, because otherwise quill does not detect changes correctly (i.e. a shallow comparison of attributes may detect that `attributes.image` has changed value, where a deep comparison would detect no difference).

For this reason, I think it's clearest if deep clones / comparisons are used everywhere.

**Comment by jhchen** [comment]
FYI I also changed rich-text to deep compare attributes like how @thomsbg has it. It still only does one level for compose, transform, etc when there is a change however.

**Comment by thomsbg** [comment]
Excellent! That fits with my usage, where changes to nested attribute keys are handled as a change to the entire attribute, e.g. concurrent changes to `src` and `caption` in my example above would not be intelligently merged.

**Comment by sachinrekhi** [comment]
Great! Just updated my python port as well to match these deep copy semantics: https://github.com/sachinrekhi/richtextpy/commit/b06297863b053a23d5bc97aa82fbbcbacd538b0f
